# Configuration for the SPEAR basic QA

input_directory: "/work/Jake.Zappala/CMIP6_output/"
output_directory: "outputs"
output_filename: "metadata_check.csv"
log_file: "metadata_check.log"

variable_name: "pr"
time_dim: "time"
lat_dim: "lat"
lon_dim: "lon"

# Threshold is the total precipitation in 6 hour window, in mm
threshold: 600.0

plot_settings:
  dpi: 150
  cmap: "Blues"
  figure_size: [4, 4]
